### ISSUE TITLE
Building process keeps failing

### ISSUE THREAD

**Issue by Gitoffomalawn** [KhasMek/gl-ar150-pineapple-firmware-builder#1]
When I run `build_pineapple.sh`, the script runs, but eventually fails after a while with the following message:

```
make: *** [world] Error 1
find: `/home/utest/gl-ar150-pineapple-firmware-builder/openwrt-cc/bin': No such file or directory
```

After I've manually added the `bin` folder to the specified path and running the script again, it runs, but then eventually fails with this message:

```
make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
make: *** [world] Error 1
utest@utest-VirtualBox:~/gl-ar150-pineapple-firmware-builder$ make -j1 V=s
make: *** No targets specified and no makefile found.  Stop.
```
I've installed all dependencies, and tried multiple OSes, all end with the same error. Any ideas?

![screenshot from 2017-04-09 19 55 21](https://cloud.githubusercontent.com/assets/25043070/24839721/410bc848-1d60-11e7-897b-0e9184071fee.png)

**Comment by KhasMek** [comment]
Looks like that was being caused by a url that has since been moved in openwrt. I have updated the submodules and tested on a clean system. It should build fine for you if you rebase off the newest commit. Thanks for the heads up and please let me know if you're still having issues after a rebase.

**Comment by Gitoffomalawn** [comment]
@KhasMek: Your fix seemed to do the trick, the script now ran till the end, and a bin file has been created. I haven't tested whether it works yet, but I'll let you know if there are any issues with it. Thanks alot!

One additional thing I feel I should mention (even though it didn't impact the build process): during the first stage of the script, when it gathers all the dependencies it needs, I noticed an error message saying it could not find `ibssl-dev`, when it should look for `libssl-dev`. It's probably just a typo somewhere in the code, and as I said, the script ran all the way through, so this may be a non-issue.

**Comment by KhasMek** [comment]
Great to hear that!

> One additional thing I feel I should mention (even though it didn't impact the build process): during the first stage of the script, when it gathers all the dependencies it needs, I noticed an error message saying it could not find ibssl-dev...

Darn it! Thanks for pointing that out. I had seen (and fixed) it while looking for the source of your issue. But, apparently then I rolled it back before pushing. I've pushed the typo fix now though.

**Comment by Gitoffomalawn** [comment]
Thanks for the speedy reaction and solution. The script runs all the way through with no errors I could spot. Issues have bee fully resolved.

Next step is using the bin, but I expect no problems. 

Thanks again for fixing everything so fast!

**Comment by xikk3x** [comment]
I run the script but it stops with the same message

make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
make: *** [world] Error 1

it looks like Gitoffomalawn sceernshot
